// src/components/Skills.vue
<template>
  <h2>Skills</h2>
  <div class="skills" @mousemove="updateMousePosition">
    <div id="tooltip" :class="{ visible: tooltipText !== '' }">
      {{ tooltipText }}
    </div>
    <img
      v-for="(skill, index) in skills"
      :key="index"
      :src="skill.image"
      :alt="skill.text"
      @mouseenter="showTooltip"
      @mouseleave="hideTooltip"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export type Skill = {
  image: string;
  text: string;
};

export default defineComponent({
  name: 'Skills',
  data() {
    return {
      tooltipText: '',
      skills: [
        {
          image: '/img/skills/react.svg',
          text: 'React'
        },
        {
          image: '/img/skills/angular.png',
          text: 'Angular'
        },
        {
          image: '/img/skills/redux.png',
          text: 'Redux'
        },
        {
          image: '/img/skills/rxjs.png',
          text: 'RxJs'
        },
        {
          image: '/img/skills/typescript.png',
          text: 'Typescript'
        },
        {
          image: '/img/skills/sass.png',
          text: 'SASS'
        },
        {
          image: '/img/skills/dotnet.png',
          text: '.Net'
        },
        {
          image: '/img/skills/nodejs.jpg',
          text: 'NodeJs'
        },
        {
          image: '/img/skills/rabbitmq.png',
          text: 'RabbitMq'
        },
        {
          image: '/img/skills/entity-framework.png',
          text: 'Entity Framework'
        },
        {
          image: '/img/skills/typeorm.png',
          text: 'Type ORM'
        },
        {
          image: '/img/skills/azure.png',
          text: 'Azure'
        },
        {
          image: '/img/skills/dev-ops.png',
          text: 'Dev Ops'
        },
        {
          image: '/img/skills/yaml.png',
          text: 'yaml'
        },
        {
          image: '/img/skills/azure-cli.png',
          text: 'Azure CLI'
        },
        {
          image: '/img/skills/gcs.png',
          text: 'Google Cloud Platform'
        },
        {
          image: '/img/skills/git.png',
          text: 'Git'
        },
        {
          image: '/img/skills/bash.png',
          text: 'Bash'
        },
        {
          image: '/img/skills/powershell.png',
          text: 'Powershell'
        },
        {
          image: '/img/skills/docker.png',
          text: 'Docker'
        },
        {
          image: '/img/skills/es-lint.png',
          text: 'ES Lint'
        },
        {
          image: '/img/skills/postman.png',
          text: 'Postman'
        },
        {
          image: '/img/skills/graphql.png',
          text: 'Graph QL'
        }
      ] as Skill[]
    };
  },
  methods: {
    showTooltip(e: MouseEvent): void {
      const target = e.target as HTMLImageElement;
      this.tooltipText = target.getAttribute('alt') as string;
    },
    hideTooltip(): void {
      this.tooltipText = '';
    },
    updateMousePosition(e: MouseEvent): void {
      const tooltip = document.getElementById('tooltip');
      if (!tooltip || !tooltip.parentElement) return;
      const rect = tooltip.getBoundingClientRect();
      const parentRect = tooltip.parentElement.getBoundingClientRect();

      const x = e.clientX - rect.width / 2 - parentRect.x;
      const y = e.clientY - rect.height - parentRect.y;

      tooltip.style.left = `${x}px`;
      tooltip.style.top = `${y}px`;
    }
  }
});
</script>

<style scoped lang="scss">
h2 {
  display: flex;
  justify-content: center;
  margin-top: 40px;
}
.skills {
  display: flex;
  flex-wrap: wrap;
  position: relative;
  margin-top: 40px;
  gap: 20px;
  justify-content: center;
  img {
    display: flex;
    height: 160px;
  }
  #tooltip {
    display: flex;
    position: absolute;
    background-color: rgba(0, 0, 0, 0.7);
    box-shadow: 0 0 3px 1px rgba(0, 0, 0, 0.3);
    color: white;
    padding: 10px 15px;
    border-radius: 15px;
    opacity: 0;
    pointer-events: none;

    &.visible {
      opacity: 1;
    }
  }
}
</style>

// src/view/skills/Skills.tsx
import './Skills.css';
import ReactTooltip from 'react-tooltip';
import ReactPng from './assets/react.svg';
import AngularPng from './assets/angular.png';
import ReduxPng from './assets/redux.png';
import RxjsPng from './assets/rxjs.png';
import TypescriptPng from './assets/typescript.png';
import SassPng from './assets/sass.png';
import DotNetPng from './assets/dotnet.png';
import NodeJsPng from './assets/nodejs.jpg';
import RabbitMqPng from './assets/rabbitmq.png';
import EntityFrameworkPng from './assets/entity-framework.png';
import TypeOrmPng from './assets/typeorm.png';
import AzurePortalPng from './assets/azure.png';
import AzureDevopsPng from './assets/dev-ops.png';
import YamlPng from './assets/yaml.png';
import AzureCliPng from './assets/azure-cli.png';
import GcsPng from './assets/gcs.png';
import GitPng from './assets/git.png';
import BashPng from './assets/bash.png';
import PowershellPng from './assets/powershell.png';
import DockerPng from './assets/docker.png';
import EsLintPng from './assets/es-lint.png';
import ResharperPng from './assets/resharper.png';
import PostmanPng from './assets/postman.png';
import GraphQlPng from './assets/graphql.png';

function Skills() {
  return (
    <div id="skill">
      <h2 className="skill-container-heading">Skills</h2>
      <div className="skill-container">
        <img src={ReactPng} alt="react" data-tip="React" />
        <img src={AngularPng} alt="angular" data-tip="Angular" />
        <img src={ReduxPng} alt="redux" data-tip="Redux" />
        <img src={RxjsPng} alt="rxjs" data-tip="RxJs" />
        <img src={TypescriptPng} alt="typescript" data-tip="Typescript" />
        <img src={SassPng} alt="sass" data-tip="CSS/SASS" />
        <img src={DotNetPng} alt="dot net" data-tip=".Net Core" />
        <img src={NodeJsPng} alt="nodejs" data-tip="NodeJs" />
        <img src={RabbitMqPng} alt="rabbit mq" data-tip="Rabbit MQ" />
        <img src={GraphQlPng} alt="graph ql" data-tip="GraphQL" />
        <img
          src={EntityFrameworkPng}
          alt="entity framework"
          data-tip="Entity Framework"
        />
        <img src={TypeOrmPng} alt="type orm" data-tip="Type ORM" />
        <img src={AzurePortalPng} alt="azure portal" data-tip="Azure Portal" />
        <img src={AzureDevopsPng} alt="azure devops" data-tip="Azure Dev Ops" />
        <img src={YamlPng} alt="yaml" data-tip="Yaml" />
        <img src={AzureCliPng} alt="azure cli" data-tip="Azure CLI" />
        <img src={GcsPng} alt="gcs" data-tip="Google Cloud Platform" />
        <img src={GitPng} alt="git" data-tip="Git" />
        <img src={BashPng} alt="bash" data-tip="Bash" />
        <img src={PowershellPng} alt="powershell" data-tip="Powershell" />
        <img src={DockerPng} alt="docker" data-tip="Docker" />
        <img src={EsLintPng} alt="es lint" data-tip="Es / TS Lint" />
        <img src={ResharperPng} alt="resharper" data-tip="Resharper" />
        <img src={PostmanPng} alt="postman" data-tip="Postman" />
      </div>
      <ReactTooltip />
    </div>
  );
}

export default Skills;
